/**
 * ProjectManager API for TypeScript
 *
 * (c) ProjectManager.com, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author     ProjectManager.com <support@projectmanager.com>
 * @copyright  ProjectManager.com, Inc.
 * @link       https://github.com/projectmgr/projectmanager-sdk-typescript
 */

import { ResourceWorkloadTaskAssignmentDto } from "../index.js";
import { ResourceWorkloadTaskDetailsDto } from "../index.js";

/**
 * A single planned allocation for a Resource on a Task, on a specific date.
 */
export type ResourceWorkloadAllocationDto = {

  /**
   * The unique identifier of this allocation, which is a combination of the TaskAssignmentId and the Date.
   */
  id: string;

  /**
   * The unique identifier of the Task this allocation belongs to.
   */
  taskId: string;

  /**
   * The unique identifier of the TaskAssignment this allocation belongs to.
   */
  taskAssignmentId: string;

  /**
   * The date this allocation applies to.
   */
  date: string;

  /**
   * The number of minutes assigned on this date.
   */
  minutes: number;

  /**
   * True if this allocation was generated by the system rather than manually set.
   */
  isSystem: boolean;

  /**
   * Basic details about the Task. Only populated when the request specifies `include=task`.
   */
  task: ResourceWorkloadTaskDetailsDto | null;

  /**
   * Details about the TaskAssignment. Only populated when the request specifies `include=taskAssignment`.
   */
  assignment: ResourceWorkloadTaskAssignmentDto | null;
};
